baseURL = "http://example.org/"
DefaultContentLanguage = "ja"
languageCode = "ja-jp"
title = "My New Hugo Nuxt Site"
author = "Kazuki"
copyright = "Copyright © 2021 Kazuki"
ignoreErrors = ["error-output-taxonomy"]

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[outputs]
home = ["JSON"]
page = ["JSON"]
section = ["JSON"]
taxonomy = ["JSON"]
